version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Start Docker Compose
          command: docker-compose up -d
          background: true      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Run tests
          command: mvn test -P login
          environment:
            BROWSER: chrome
      - store_artifacts:
          path: target/surefire-reports/*.html
          destination: test-results
      - run:
          name: Stop Docker Compose
          command: docker-compose down          

# run jobs parallely
workflows:
  build_and_test:
    jobs:
      - build:
          parallelism: 2
          filters:
            branches:
              only: main
