version: "3"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    container_name: chrome
    environment:
      HUB_HOST: selenium-hub
    depends_on:
      - selenium-hub

  firefox:
    image: selenium/node-firefox:latest
    container_name: firefox
    environment:
      HUB_HOST: selenium-hub
    depends_on:
      - selenium-hub

  edge:
    image: selenium/node-edge:latest
    container_name: edge
    environment:
      HUB_HOST: selenium-hub
    depends_on:
      - selenium-hub
