name: Selenium Demo Project
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
      - name: Compile and build
        run: mvn package 
      - name: Run Tests
        run: mvn test 